version: "3.8"
services:
    viaplay_backend:
      build: 
        context: .
        dockerfile: ./Dockerfile
      stop_signal: SIGINT
      container_name: viaplay_api_service
      image: viaplay_backend
      ports:
        - "9000:9000"
      # ? For automatically updating the container (for development only)
      volumes:
        - .:/app
      restart: always

    viaplay_database:
      image: mongo
      container_name: viaplay_db_service
      ports:
        - "27017:27017"
      volumes:
        - /data/db:/data/db
      restart: unless-stopped